name: Deploy on GitHub Pages
run-name: ${{ github.actor }} Request deploy on GitHub Pages 🚀
on:
  push:
    tags:
      - v*
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3

      - run: npm install --read-only-lockfile

      - run: npm run deploy
